services:
  web-dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: django_dev_app
    volumes:
      - .:/app
      # Montar las credenciales de Git desde Windows
      - ${USERPROFILE}/.gitconfig:/root/.gitconfig:ro
      - ${USERPROFILE}/.git-credentials:/root/.git-credentials:ro
      # Si usas SSH para Git
      - ${USERPROFILE}/.ssh:/root/.ssh:ro
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
    stdin_open: true
    tty: true

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  mongo_data:
