# Generated by Django 5.2.7 on 2025-10-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    # pyrefly: ignore  # bad-override
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("contenido", models.TextField()),
            ],
        ),
    ]
